# Generated by Django 4.2.16 on 2026-02-25 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_dailymotivationquote_passwordresetotp_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='title',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
