# Generated by Django 4.2.16 on 2026-02-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_passwordresetotp_title_chatsession_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymotivationquote',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='dailymotivationquote',
            name='text',
            field=models.TextField(),
        ),
    ]
