# Generated by Django 4.2.16 on 2026-02-25 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_remove_dailymotivationquote_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', 'Great'), ('angry', 'Angry'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('sad', 'Sad')], max_length=20)),
                ('stress_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', 'Great'), ('angry', 'Angry'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('sad', 'Sad')], max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['mood', 'order'],
                'unique_together': {('mood', 'order')},
            },
        ),
        migrations.CreateModel(
            name='MoodOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=120)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='myapp.moodquestion')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MoodCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('great', 'Great'), ('angry', 'Angry'), ('tired', 'Tired'), ('stressed', 'Stressed'), ('sad', 'Sad')], max_length=20)),
                ('stress_level', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_checkins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoodAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(blank=True, default='', max_length=255)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.moodcheckin')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.moodquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.moodoption')),
            ],
            options={
                'unique_together': {('checkin', 'question')},
            },
        ),
    ]
