# Generated by Django 4.2.16 on 2026-02-26 09:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_moodsession_moodquestion_moodoption_moodcheckin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodanswer',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='moodanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='moodanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moodanswer',
            name='question_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodanswer',
            name='question_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='moodanswer',
            name='selected_option_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='moodanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='myapp.moodquestion'),
        ),
        migrations.AlterField(
            model_name='moodanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answers', to='myapp.moodoption'),
        ),
        migrations.AlterField(
            model_name='moodsession',
            name='stress_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='moodanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('checkin', 'question'), name='uniq_checkin_question_when_question_set'),
        ),
        migrations.AddConstraint(
            model_name='moodanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('question_no__isnull', False)), fields=('checkin', 'question_no'), name='uniq_checkin_questionno_when_questionno_set'),
        ),
    ]
