# Generated by Django 4.2.16 on 2026-02-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_moodanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodanswer',
            options={'ordering': ['question_no']},
        ),
        migrations.RemoveConstraint(
            model_name='moodanswer',
            name='uniq_checkin_question_when_question_set',
        ),
        migrations.RemoveConstraint(
            model_name='moodanswer',
            name='uniq_checkin_questionno_when_questionno_set',
        ),
        migrations.AlterField(
            model_name='moodanswer',
            name='question_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='moodanswer',
            unique_together={('checkin', 'question_no')},
        ),
        migrations.RemoveField(
            model_name='moodanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='moodanswer',
            name='selected_option',
        ),
    ]
