# Generated by Django 4.2.16 on 2026-02-26 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0014_musictrack_usermusicstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_seconds', models.PositiveIntegerField(default=0)),
                ('steps_total', models.PositiveIntegerField(default=12)),
                ('steps_completed', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_scan_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BodyScanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('emoji', models.CharField(blank=True, default='', max_length=10)),
                ('instructions', models.TextField(blank=True, default='')),
                ('position_tip', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('tense_seconds', models.PositiveIntegerField(default=5)),
                ('hold_seconds', models.PositiveIntegerField(default=3)),
                ('release_seconds', models.PositiveIntegerField(default=5)),
                ('rest_seconds', models.PositiveIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BodyScanStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('TENSE', 'TENSE'), ('HOLD', 'HOLD'), ('RELEASE', 'RELEASE'), ('REST', 'REST'), ('SKIP', 'SKIP')], max_length=10)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapp.bodyscansession')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bodyscanstep')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
