# Generated by Django 4.2.16 on 2026-02-27 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0015_bodyscansession_bodyscanstep_bodyscansteplog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='musictrack',
            name='bpm',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature Sounds'), ('music', 'Music')], default='nature', max_length=20),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='musictrack',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='musictrack',
            name='mood',
            field=models.CharField(blank=True, choices=[('', 'None'), ('calm', 'Calm'), ('happy', 'Happy'), ('focus', 'Focus'), ('energize', 'Energize'), ('sleep', 'Sleep'), ('meditative', 'Meditative')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermusicstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SoundPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='myapp.musictrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_plays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
