# Generated by Django 4.2.16 on 2026-03-02 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0017_feedback_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('morning', 'Morning Calm'), ('stress', 'Stress Relief'), ('deep', 'Deep Relaxation'), ('sleep', 'Sleep Preparation')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='meditations/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeditationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='myapp.meditationprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
