# Generated by Django 4.2.16 on 2026-03-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_meditationprogram_meditationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='app_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ta', 'Tamil')], default='en', max_length=10),
        ),
    ]
